### PR TITLE
Adding copy formatting function to package

### PR DESCRIPTION
**Pull request by DIPAD-Fran-Bryden**
## As a contributor 
By submitting this PR I confirm I have read and understood the Github Standards document and understand the role I play in ensuring standards, security, and assurance at DfT.

## As a PR reviewer
By accepting this PR I understand my responsibilities as described in the the Github standards document.

# Proposed changes

Added copy formatting function to package, including minor changes to improve speed and clarity of function

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (change which fixes an issue)
- [X] New feature (change which adds functionality)
- [X] Documentation Update (change to naming or other documentation)

## Points I have checked in my code

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR._

- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)
- [X] I have checked that my changes have not broken any other functionality
- [ ] I have linked to any issues this PR fixes 

## Points for review

Add checkboxes here for any specific aspects of your PR you would like to be checked in peer review. If you don't specify anything here, the reviewer will check:

- [ ] All of your unit tests pass
- [ ] Your code is clear and easy to understand
- [ ] You have documented any new features
- [ ] They can run the code you have written
- [ ] Your changes do not break any other functionality

## Security considerations

_Put an `x` in the boxes that apply. You should have considered all of these points before submitting a PR._

- [X] My code does not contain any secrets such as passwords, API keys, etc
- [X] I have not accidentally uploaded any data to Github
- [X] My code does not include any personal information such as names or email addresses

## Who is reviewing this PR?

Tag your reviewer here to ensure they get a notification!

### CODE REVIEW

**Comment by DIPAD-Fran-Bryden** [comment]
@AIMS-Sean-Longman planning to incorporate your function into main with this PR 🥇 I was looking in to whether it could be vectorised (e.g. providing more than one colTo and the rows as a single vector rather than a from and to value), can you think of any reason this would break the intended behaviour of the function? And would you be willing to do a peer review on the code once I've made that change?

**Comment by AIMS-Sean-Longman** [comment]
@DIPAD-Fran-Bryden Like the addition of the sapply to filter the styles object!! Wish I'd thought of that! Regarding vectorising the colTo and row, I think you can have colTo as a vector already? Because the code puts in each style row by row, addStyle can handle an unequal row vector and col vector as long as one of them is length 1 which would be the row. Vectorising the row rather than startRow and endRow will need an adjustment for the looping through each row (I'm assuming non-consecutive rows), but is doable, and shouldn't break the functionality. As long as colFrom and sheet are single values, can't see anything breaking.

Of course happy to peer review

**Comment by DIPAD-Fran-Bryden** [comment]
@AIMS-Sean-Longman sorted and all ready for your review! I can't tag you in it until you accept the invite to the repo, but would appreciate any thoughts you have 😺

**Review by AIMS-Sean-Longman — APPROVED** [review]
I've tested this across non-consecutive rows, consecutive rows, multiple columns for the colTo argument. I'm happy that this works as intended. I'm happy with the update to the ReadMe. Very excited to see this being used.

**Pull request merged**
